Weight: False

BBC:
  View_num: 4
  lr: [0.01]
  l2_coef: [0.001]
  reg_coef: [0.001]
  hid: [256]
  sc: 10
  nb_epochs: 500
  norm: False

LandUse-21:
  View_num: 3
  lr: [0.0001]
  l2_coef: [0.01]
  reg_coef: [0.01]
  hid: [512]
  sc: 10
  nb_epochs: 500
  norm: False

BBCSport:
  View_num: 2
  lr: [0.001]
  l2_coef: [0.001]
  reg_coef: [0.00001]
  hid: [512]
  sc: 100
  nb_epochs: 500
  norm: False




small_Reuters:
  View_num: 5
  lr: [0.01]
  l2_coef: [0.001]
  reg_coef: [0.0001]
  hid: [256]
  sc: 10
  nb_epochs: 500
  norm: False

Reuters:
  View_num: 5
  lr: [0.001]
  l2_coef: [0.00001]
  reg_coef: [0.00001]
  hid: [256]
  sc: 10
  nb_epochs: 500
  norm: False


MSRCv1:
  View_num: 5
  lr: [0.01]
  l2_coef: [0.0001]
  reg_coef: [0.01]
  hid: [64]
  sc: 10
  nb_epochs: 500
  norm: False

#  lr: [ 0.001 ]
#  l2_coef: [ 0.0005 ]
#  reg_coef: [ 0.1 ]
#  hid: [ 64 ] #64
#  isMeanOrCat: 'Cat'
#  sc: 10
#  nb_epochs: 500
#  isAttn: False
#  norm: False

small_NUS:
  View_num: 5
  lr: [0.0001]
  l2_coef: [0.00001]
  reg_coef: [0.0001]
  hid: [512]
  sc: 10
  nb_epochs: 500
  norm: False



3sources:
  View_num: 3
  lr: [0.001]
  l2_coef: [0.0001]
  reg_coef: [0.0001]
  hid: [128]
  sc: 10
  nb_epochs: 500
  norm: False


HW:
  View_num: 6
  lr: [0.01,0.001,0.0001]
  l2_coef: [0.0005]
  reg_coef: [0.01,0.001,0.0001]
  hid: [512]
  sc: 10
  nb_epochs: 500
  norm: False



NUSWIDEOBJ:
  View_num: 5
  lr: [0.001]
  l2_coef: [0.0005]
  reg_coef: [0.001,0.0001]
  hid: [64]
  sc: 3
  nb_epochs: 500
  norm: False

yale_mtv:
  View_num: 3
  lr: [0.001]
  l2_coef: [0.0001]
  reg_coef: [0.01]
  hid: [256]
  sc: 10
  nb_epochs: 500
  norm: False
#======================

#movies617:
#  View_num: 2
#  lr: [ 0.0001 ]
#  l2_coef: [ 0.0005 ]
#  reg_coef: [ 1 ]
#  hid: [ 128 ]
#  isMeanOrCat: 'Cat'
#  sc: 10
#  nb_epochs: 500
#  isAttn: False
#  norm: False



ORL_mtv:
  View_num: 3
  lr: [0.001]
  l2_coef: [0.0001]
  reg_coef: [0.1,0.01,0.001,0.0001]
  hid: [256,512]
  sc: 3
  nb_epochs: 500
  norm: False

flower17:
  View_num: 7
  lr: [0.01,0.001,0.0001]
  l2_coef: [10,1,0.1,0.01,0.001,0.0001]
  reg_coef: [10,1,0.1,0.01,0.001,0.0001]
  hid: [256,512]
  sc: 10
  nb_epochs: 500
  norm: False



citeseer:
  View_num: 2
  lr: [0.01,0.001,0.0001]
  l2_coef: [10,1,0.1,0.01,0.001,0.0001]
  reg_coef: [10,1,0.1,0.01,0.001,0.0001]
  hid: [256,512]
  sc: 10
  nb_epochs: 500
  norm: False

