Weight: False

BBC:
  View_num: 4
  lr: [0.0002]
  l2_coef: [0.0005]
  reg_coef: [0.0001]
  hid: [512]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 1000
  isAttn: True
  norm: True

BBCSport:
  View_num: 2
  lr: [0.0001]
  l2_coef: [0.0005]
  reg_coef: [0.1,0.01,0.001,0.0001]
  hid: [256]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 1000
  isAttn: True
  norm: True




small_Reuters:
  View_num: 5
  lr: [ 0.01 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1]
  hid: [ 64 ]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 100
  isAttn: True
  norm: True

Reuters:
  View_num: 5
  lr: [ 0.01 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1 ]
  hid: [ 64 ]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 100
  isAttn: True
  norm: True


MSRCv1:
  View_num: 5
  lr: [ 0.001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1 ]
  hid: [ 64 ] #64
  isMeanOrCat: 'Cat'
  sc: 10
  nb_epochs: 1000
  isAttn: False
  norm: True





3sources:
  View_num: 3
  lr: [ 0.1,0.01,0.001,0.0001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1,0.01,0.001,0.0001 ]
  hid: [ 64,128 ]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 1000
  isAttn: True
  norm: True


HW:
  View_num: 6
  lr: [ 0.00001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1 ]
  hid: [ 128 ]
  isMeanOrCat: 'Cat'
  sc: 10
  nb_epochs: 1000
  isAttn: False
  norm: False

small_NUS:
  View_num: 5
  lr: [ 0.0001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1 ]
  hid: [ 64 ]
  isMeanOrCat: 'Cat'
  sc: 10
  nb_epochs: 1000
  isAttn: False
  norm: False

NUSWIDEOBJ:
  View_num: 5
  lr: [ 0.0001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 1 ]
  hid: [ 128 ]
  isMeanOrCat: 'Cat'
  sc: 10
  nb_epochs: 1000
  isAttn: False
  norm: False

yale_mtv:
  View_num: 3
  lr: [ 0.00005 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1]
  hid: [ 128  ]
  isMeanOrCat: 'Cat'
  sc: 10
  nb_epochs: 10000
  isAttn: False
  norm: False
#======================

#movies617:
#  View_num: 2
#  lr: [ 0.0001 ]
#  l2_coef: [ 0.0005 ]
#  reg_coef: [ 1 ]
#  hid: [ 128 ]
#  isMeanOrCat: 'Cat'
#  sc: 10
#  nb_epochs: 1000
#  isAttn: False
#  norm: False



ORL_mtv:
  View_num: 3
  lr: [ 0.00005 ]
  l2_coef: [ 0.005 ]
  reg_coef: [ 0.1 ]
  hid: [ 128]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 10000
  isAttn: True
  norm: True

flower17:
  View_num: 7
  lr: [ 0.005 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.1 ]
  hid: [ 128 ]
  isMeanOrCat: 'cat'
  sc: 10
  nb_epochs: 1000
  isAttn: False
  norm: False



citeseer:
  View_num: 2
  lr: [ 0.001 ]
  l2_coef: [ 0.0005 ]
  reg_coef: [ 0.01 ]
  hid: [ 128 ]
  isMeanOrCat: 'Mean'
  sc: 10
  nb_epochs: 1000
  isAttn: True
  norm: False

